services:
  api:
    build: .
    container_name: rentathing-api
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql+asyncpg://postgres:1008@db:5432/rentathing
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: rentathing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1008"
      POSTGRES_DB: rentathing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: rentathing-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: rentathing-celery-worker
    command: celery -A app.tasks.worker.celery_app worker --loglevel=INFO
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql+asyncpg://postgres:1008@db:5432/rentathing
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - api
      - redis
    restart: unless-stopped

volumes:
  postgres_data:

