"""Add email verification fields

Revision ID: 869f0254eeab
Revises: 722acced9bf9
Create Date: 2026-09-30 14:06:23.586818

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql


revision = '869f0254eeab'
down_revision = '722acced9bf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###

